version: 2
jobs:
  test-job:
    docker:
       - image: circleci/ruby:2.6.3-node-browsers
       - image: mongo:4.1.4-xenial
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "Gemfile.lock" }}
          - v1-dependencies-
      - run:
          name: install dependencies
          command: |
            bundle install --jobs=4 --retry=3 --path vendor/bundle
      - save_cache:
          paths:
            - ./vendor/bundle
          key: v1-dependencies-{{ checksum "Gemfile.lock" }}
      - run:
          name: run tests
          command: |
            bundle exec rspec --format html --out /tmp/rspec.html --format progress
      - store_test_results:
          path: /tmp/test-results
      - store_artifacts:
          path: /tmp/test-results
          destination: test-results
  deploy-job:
    docker:
       - image: circleci/ruby:2.6.3-node-browsers
       - image: mongo:3.6.12-xenial
    working_directory: ~/repo
    steps:
      - add_ssh_keys:
          fingerprints:
            - "fa:fe:e6:76:13:de:d6:1b:cc:5a:3d:42:3f:60:17:01"
      - checkout
      - run:
          name: Bundle Install
          command: bundle check || bundle install
      - run:
          name: Deploy to production environment
          command: bundle exec cap production deploy
workflows:
  version: 2
  build-deploy:
    jobs:
      - test-job
      - deploy-job:
          requires:
            - test-job
          filters:
            branches:
              only: master